name: Deploy to Google Cloud Platform

on:
  push:
    branches:
      - main 

permissions:  
  contents: read 
  id-token: write  

jobs: # A job is a set of steps that execute on the same runner
  deploy:
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout Code  
      uses: actions/checkout@v2

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: 'projects/359910979371/locations/global/workloadIdentityPools/github/providers/static-website-pool'
        service_account: 'static-website-service-account@cloudcomputing-411615.iam.gserviceaccount.com'

    - name: Deploy to Google Cloud Storage  
      run: gsutil rsync -r ${{github.workspace}} gs://static_website_storage

